pipeline {
     agent {
       kubernetes {
         yaml """
   apiVersion: v1
   kind: Pod
   metadata:
     name: kaniko
   spec:
     containers:
     - name: kaniko
       image: gcr.io/kaniko-project/executor:debug
       workingDir: /home/jenkins/agent
       imagePullPolicy: Always
       command:
         - /busybox/cat
       tty: true
       volumeMounts:
         - name: kaniko-secret
           mountPath: /kaniko/.docker
     restartPolicy: Never
     volumes:
       - name: kaniko-secret
         secret:
           secretName: dockercredentials
           items:
             - key: .dockerconfigjson
               path: config.json
   """
       }
     }
     stages {
       stage("Clone"){
         steps{
           git 'https://github.com//manshaaazar/reactStone.git'
         }
       }
       stage("Build Image") {
         steps {
           container(name: "kaniko", shell: "/busybox/sh") {
   
             sh """#!/busybox/sh
                           /kaniko/executor --context ./  --destination manshaehsan/knight:kaniko
                 """
           }
         }
       }
     }
   }
   pipeline {
     agent {
       kubernetes {
         yaml """
   apiVersion: v1
   kind: Pod
   metadata:
     name: kaniko
   spec:
     containers:
     - name: kaniko
       image: gcr.io/kaniko-project/executor:debug
       workingDir: /home/jenkins/agent
       imagePullPolicy: Always
       command:
         - /busybox/cat
       tty: true
       volumeMounts:
         - name: kaniko-secret
           mountPath: /kaniko/.docker
     restartPolicy: Never
     volumes:
       - name: kaniko-secret
         secret:
           secretName: dockercredentials
           items:
             - key: .dockerconfigjson
               path: config.json
   """
       }
     }
     stages {
       stage("Clone"){
         steps{
           git 'https://github.com//manshaaazar/reactStone.git'
         }
       }
       stage("Build Image") {
         steps {
           container(name: "kaniko", shell: "/busybox/sh") {
   
             sh """#!/busybox/sh
                           /kaniko/executor --context ./  --destination manshaehsan/knight:kaniko
                 """
           }
         }
       }
     }
   }
   pipeline {
     agent {
       kubernetes {
         yaml """
   apiVersion: v1
   kind: Pod
   metadata:
     name: kaniko
   spec:
     containers:
     - name: kaniko
       image: gcr.io/kaniko-project/executor:debug
       workingDir: /home/jenkins/agent
       imagePullPolicy: Always
       command:
         - /busybox/cat
       tty: true
       volumeMounts:
         - name: kaniko-secret
           mountPath: /kaniko/.docker
     restartPolicy: Never
     volumes:
       - name: kaniko-secret
         secret:
           secretName: dockercredentials
           items:
             - key: .dockerconfigjson
               path: config.json
   """
       }
     }
     stages {
       stage("Clone"){
         steps{
           git 'https://github.com//manshaaazar/reactStone.git'
         }
       }
       stage("Build Image") {
         steps {
           container(name: "kaniko", shell: "/busybox/sh") {
   
             sh """#!/busybox/sh
                           /kaniko/executor --context ./  --destination manshaehsan/knight:kaniko
                 """
           }
         }
       }
     }
   }
   