# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Cloning Code
        uses: actions/checkout@v2
        with:
          repository: https://github.com/manshaazar/d-front.git  
          ref: login-page
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Testing App
        run: echo "Lets start"  
  containerization:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
     - name: Setting Up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Setting up Docker
       uses: docker/setup-buildx-action@v1
